### ISSUE TITLE
Rating bonus for ending win streaks

### ISSUE THREAD

**Issue by FabioCashflo** [paralin/WebLeagueIssues#25]
Together with K and Likeood add a bonus in the Elo change calculation given the current win streak of each player. 

To the BASE Elo change we can add a value (New Win Streak - 1)_0.05_BASE change. 

So, the final new elo change will be : Old Elo + Base Elo Change + (New Win Streak - 1)_0.05_Base Elo Change. 

New means winstreak value AFTER the match that will be = OLD winstreak + 1 in case of Win  or = 0 in case of Lost

**Comment by paralin** [comment]
done
