### ISSUE TITLE
Announcement in banner

### ISSUE THREAD

**Issue by Mikeylicious** [paralin/WebLeagueIssues#28]
Format:

Date - Season X
Prizepool: XXXXXXXe

make it cool like /r/dota2 does in their banner

**Comment by paralin** [comment]
Can you give me some kind of an idea of how it would look? The banner is completely different from /r/dota2, you keep seeming to forget this... 

https://www.youtube.com/watch?v=ZAc51_0Xa_M

**Comment by Mikeylicious** [comment]
Can we try something like this: 
http://i.imgur.com/e6XQXoH.png

One above another (would kinda make banner bigger right? thats bad)
Or one next to eachother (ideal)
LOGO + 3 liners
