### ISSUE TITLE
Colours for admins and other ranks

### ISSUE THREAD

**Issue by Mikeylicious** [paralin/WebLeagueIssues#29]
Making it more easier for the eye, i always asked for colour-whiteish...it standsout too much atm.
Also get us a colour for the ''Voucher'' title

**Comment by paralin** [comment]
Please give me some color options and there is a color for the voucher title already.

**Comment by Mikeylicious** [comment]
hmm was stupid of me to ask about this so soon, lets wait until we apply the final design and faceit colour scheme later on
Then we can judge colours i guess
