### ISSUE TITLE
Match result 1398737806

### ISSUE THREAD

**Issue by Mikeylicious** [paralin/WebLeagueIssues#41]
http://cs622529.vk.me/v622529812/2a467/G_su9Bnt-Ao.jpg  -evidence

dno nicknames...i can ask  or maybe u can see in history. It's played exactly 16-18 hours ago

**Comment by paralin** [comment]
Unknown players: clockwork (loss), so many pros! (winner)

**Comment by paralin** [comment]
Win/loss applied except for unknowns

**Comment by paralin** [comment]
Ubah is clockwork

**Comment by paralin** [comment]
I THINK I applied this one. If people complain I didn't.
