### ISSUE TITLE
Remove all pick

### ISSUE THREAD

**Issue by Mikeylicious** [paralin/WebLeagueIssues#49]
remove ap, its useless. Noone played it and several players confirmed the removal.

Funn1k wants ardm and i confirm ardm was played REGULARLY back befor ein inhouse leagues and its very competitive mode. It's just nowadays tournaments make ardm like a goofy match. Actually ARDM is very very tense and competitive.

So just replace these two.

**Comment by paralin** [comment]
We are considering adding ARDM as an unranked thing for studio time. For now we are removing ap

**Comment by paralin** [comment]
done
