### ISSUE TITLE
STUFF

### ISSUE THREAD

**Issue by ixmike88** [paralin/WebLeagueIssues#69]
timestamp tooltips show up in whitespace in chat
timestamp time is incorrect, shows current time
player list/ratings should be a two column grid
fpl month1/week1 ladders arent the same (?)
fpl week needs to start on the 4th
message of the day feature
i need some type of censor strike system
i need some query/filter stuff for users (vouched user list output, # vouch count, users with no games, etc)
game is full sound
autostart by default on hostbot (can be shut off in client)
need public leaderboard

**Comment by paralin** [comment]
splitting into multiple issues

**Comment by paralin** [comment]
ladder differences was because theres 1 extra game on the weekly ladder
